@startuml
'https://plantuml.com/sequence-diagram

package "ui" {
    package "swing" {

    }
}

package "domain" {

}

package "dao" {

    package "query" {

    }

    package "impl" {

    }

    package "config" {

    }

}




@enduml