package ua.birthdays.app.dao.env;

public enum EnumStateSorted {
    ASCENDING_NAME_FRIEND,
    DESCENDING_NAME_FRIEND,
    ASCENDING_FRIEND_BIRTHDAY_DATE,
    DESCENDING_FRIEND_BIRTHDAY_DATE,
    DEFAULT
}
